
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team02-s24-4pm-6
owner: ucsb-cs156-s24
repo_name: team02-s24-4pm-6
pull_requests: [{"author":{"id":"U_kgDOBXuvwQ","is_bot":false,"login":"brycewangg","name":"Bryce Wang"},"headRefName":"Bryce-MenuItemReviewController","number":54,"title":"Create controller and add get and post","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-6/pull/54"},{"author":{"id":"MDQ6VXNlcjI0NzgzNDE3","is_bot":false,"login":"dakotazoid56","name":"Dakota"},"headRefName":"Dakota-RecRequest-controller","number":53,"title":"Dakota RecRequest Controller and Tests for GET, POST, DELETE, PUT","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-6/pull/53"},{"author":{"id":"MDQ6VXNlcjI0NzgzNDE3","is_bot":false,"login":"dakotazoid56","name":"Dakota"},"headRefName":"Dakota-RecRequest-create-db","number":52,"title":"Dakota - RecRequest add entity, repository, changes files","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-6/pull/52"}]
