
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team02-s24-4pm-6
owner: ucsb-cs156-s24
repo_name: team02-s24-4pm-6
pull_requests: [{"author":{"id":"MDQ6VXNlcjg5NTU1MzQw","is_bot":false,"login":"nbelle1","name":"Nik Belle"},"headRefName":"Nik-UCSBOrganization","number":47,"title":"NB - finish controller get and post","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-6/pull/47"},{"author":{"id":"U_kgDOBXuvwQ","is_bot":false,"login":"brycewangg","name":"Bryce Wang"},"headRefName":"Bryce-MenuItemReview","number":45,"title":"Create database for MenuItemReview","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-6/pull/45"},{"author":{"id":"U_kgDOCeKwaw","is_bot":false,"login":"ok-at-computers","name":"Kevin"},"headRefName":"Kevin-Articles","number":44,"title":"PR for Articles","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-6/pull/44"}]
