
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team02-s24-4pm-6
owner: ucsb-cs156-s24
repo_name: team02-s24-4pm-6
pull_requests: [{"author":{"id":"MDQ6VXNlcjI0NzgzNDE3","is_bot":false,"login":"dakotazoid56","name":"Dakota"},"headRefName":"Dakota-RecRequest-create-db","number":52,"title":"Dakota - RecRequest add entity, repository, changes files","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-6/pull/52"},{"author":{"id":"U_kgDOB740jQ","is_bot":false,"login":"sawyerrice","name":""},"headRefName":"Sawyer-UCSBDiningMenu","number":51,"title":"Adding Delete, Put, Get to UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-6/pull/51"},{"author":{"id":"MDQ6VXNlcjg5NTU1MzQw","is_bot":false,"login":"nbelle1","name":"Nik Belle"},"headRefName":"Nik-OrganizationControllerPut","number":50,"title":"Added Put function to edit an organization","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-6/pull/50"},{"author":{"id":"U_kgDOCeKwaw","is_bot":false,"login":"ok-at-computers","name":"Kevin"},"headRefName":"Kevin-Articles","number":44,"title":"PR for Articles","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-6/pull/44"}]
